reset_filter:
  fields:
    device_id:
      selector:
        device:
          integration: petkit_ble

set_device_config:
  fields:
    device_id:
      selector:
        device:
          integration: petkit_ble
    smart_time_on:
      example: 30
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
    smart_time_off:
      example: 60
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
    led_brightness:
      example: 80
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    led_switch:
      selector:
        boolean:
    do_not_disturb:
      selector:
        boolean:
    is_locked:
      selector:
        boolean:
