name: Validate HACS

on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"
